os: linux
dist: trusty
branches:
  only:
    - development
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
#tag: true
jobs:
  include:
    - stage: travis
      name: travis_test
      script: bash travis_build.sh